import { siteConfig } from "@/lib/site";

export const metadata = {
  title: "Privacy Policy",
};

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <div className="space-y-3">
        <p className="text-sm font-semibold uppercase tracking-[0.3em] text-muted">
          Privacy
        </p>
      <h1 className="font-sans text-[1.85rem] font-bold tracking-[-0.04em] text-foreground sm:text-[2.15rem]">
          Privacy Policy
        </h1>
        <p className="text-base leading-7 text-muted">
          {siteConfig.name} only processes the data needed to run the shop,
          fulfill orders, and provide support.
        </p>
      </div>

      <section className="card space-y-3 text-sm leading-7 text-muted">
        <h2 className="font-sans text-2xl font-bold tracking-[-0.04em] text-foreground">
          What We Collect
        </h2>
        <p>
          When you place an order, we may process your name, email address,
          shipping details, the items you purchase, and payment-related
          references returned by our payment providers.
        </p>
        <p>
          We also process technical data required to run the website securely,
          such as basic request logs and anti-fraud information generated by our
          hosting and payment partners.
        </p>
      </section>

      <section className="card space-y-3 text-sm leading-7 text-muted">
        <h2 className="font-sans text-2xl font-bold tracking-[-0.04em] text-foreground">
          How Data Is Used
        </h2>
        <p>We use order data to:</p>
        <ul className="space-y-2">
          <li>process and confirm orders</li>
          <li>arrange shipping or local pickup</li>
          <li>handle refunds, returns, and support requests</li>
          <li>prevent abuse and keep the store secure</li>
        </ul>
      </section>

      <section className="card space-y-3 text-sm leading-7 text-muted">
        <h2 className="font-sans text-2xl font-bold tracking-[-0.04em] text-foreground">
          Third-Party Services
        </h2>
        <p>
          Payments are processed by Stripe and, when configured, PayPal. Order
          emails are sent through Mailgun. Product and storefront data are hosted
          through Vercel and PostgreSQL infrastructure selected by the store
          operator.
        </p>
      </section>

      <section className="card space-y-3 text-sm leading-7 text-muted">
        <h2 className="font-sans text-2xl font-bold tracking-[-0.04em] text-foreground">
          Contact
        </h2>
        <p>
          For privacy questions or deletion requests, contact{" "}
          <span className="font-medium text-foreground">
            {siteConfig.legal.contactEmail}
          </span>
          .
        </p>
      </section>
    </div>
  );
}
